### ISSUE TITLE
create entity-relationship (ER) diagram

### ISSUE THREAD

**Issue by thewro11** [samoonpride/api-backend#1]
In order to create the backend service, we need to know what and how many entities (along with their attributes) we should have to create the database.

Acceptance Criteria:
- Create entity-relationship diagram with appropriate entities along with their attributes and relationships between entities.

**Comment by thewro11** [comment]
Database should also keep system "log" too.

**Comment by Natdadai** [comment]
[ER Diagram](https://app.diagrams.net/#G1qKL4iB5p3ZmRQr9NCsA77s38NuJzblWq#%7B%22pageId%22%3A%22UNFEQTNDf9xjKw_W8duf%22%7D)
![Image](https://github.com/samoonpride/api-backend/assets/78583507/ba8b42ad-3c43-442f-8e57-9e04cee50f71)
