### ISSUE TITLE
initialize API backend server repository

### ISSUE THREAD

**Issue by thewro11** [samoonpride/api-backend#2]
As we have discussed about system architecture of this project. We decided to have 3 micro-services including API backend, Line webhook frontend, and web application frontend. For this instance, we need to initialize the API backend server to be working on the next progressing steps.

Acceptance Criteria:
- The API backend server is successfully initialized.
- Setup `docker compose up` command to also run the backend application along with MySQL server.

**Comment by thewro11** [comment]
The acceptance criteria of this issue has been updated. It is now:
- The API backend server is successfully initialized.
- Setup `docker compose up` command to also run the backend application along with MySQL server.

**Comment by thewro11** [comment]
You can commit your code to `main`. You don't have to create any additional branches at this moment.

**Comment by Natdadai** [comment]
You can view in this commit [297ff33](https://github.com/samoonpride/api-backend/commit/297ff33b0af1de932c91dd261355e6d3daf7812f)
